name = "Practicas"
version = "0.1.0"
license = "license"
author = "Franklin ONP"
maintainer = "3110022770701@ingenieria.usac.edu.gt"
copyright = "Copyright 2024, Franklin ONP"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

